### PR TITLE
Wratil22

### PR DESCRIPTION
**Pull request by zachandfox**
[Issue #346](https://github.com/hivdb/covid-drdb-payload/issues/346)

### CODE REVIEW

**Comment by KaimingTao** [comment]
@zachandfox please see the build details, I think the error message is self-explanatory.

**Comment by zachandfox** [comment]
@KaimingTao Not sure why it's not accepting IC50

**Comment by KaimingTao** [comment]
@zachandfox I think it's plasma data, so the potency type is `NTxx` like `NT50`. So the potency unit is NULL.

**Comment by KaimingTao** [comment]
@zachandfox even the paper is using `IC50`, they're actually `NT50`.  You can also find it because the figures are using ratio y-scale.

**Pull request merged**
