### PR TITLE
 Arora22c - 10.1016/j.celrep.2022.110754 #480 

### PR DESCRIPTION
**Pull request by zachandfox**
Arora22c - 10.1016/j.celrep.2022.110754 #480

### CODE REVIEW

**Comment by zachandfox** [comment]
I'm not sure I understand the error in [30b2b66](https://github.com/hivdb/covid-drdb-payload/pull/514/commits/30b2b66676e354d2c1835a3626df11fd777ffbf6). I thought it had to do with specifying `0.002` as the `potency_lower_limit`, so I set it to `1` but still produced the same error in [12977b6](https://github.com/hivdb/covid-drdb-payload/pull/514/commits/12977b6b3c77018c51dbb69f321554c2e515bd7a).

**Comment by zachandfox** [comment]
Also, for unspecified IC50 values that are beyond the limits of detection, do we set it to 1 (like in NT50) or the upper limit?

**Comment by KaimingTao** [comment]
> I'm not sure I understand the error in [30b2b66](https://github.com/hivdb/covid-drdb-payload/pull/514/commits/30b2b66676e354d2c1835a3626df11fd777ffbf6). I thought it had to do with specifying `0.002` as the `potency_lower_limit`, so I set it to `1` but still produced the same error in [12977b6](https://github.com/hivdb/covid-drdb-payload/pull/514/commits/12977b6b3c77018c51dbb69f321554c2e515bd7a).

Please change the `potency_unit`, most of time for IC50 it's `ng/ml`

**Comment by KaimingTao** [comment]
> Also, for unspecified IC50 values that are beyond the limits of detection, do we set it to 1 (like in NT50) or the upper limit?

We set to the upper limit.

**Pull request merged**
