### PR TITLE
 Aggarwal22 - 10.1038/s41564-022-01135-7 #628 

### PR DESCRIPTION
**Pull request by zachandfox**
Aggarwal22 - 10.1038/s41564-022-01135-7 #628

### CODE REVIEW

**Comment by KaimingTao** [comment]
@zachandfox this paper is a published preprint, we don't need to reenter it. Please ignore all the files that start with `dms`, you don't need to submit them. Currently, we have an issue between database and website, may take some time to update it.,

**Comment by zachandfox** [comment]
> @zachandfox this paper is a published preprint, we don't need to reenter it. Please ignore all the files that start with `dms`, you don't need to submit them. Currently, we have an issue between database and website, may take some time to update it.,

The `dms` changes were done by running `make autofill`, and I had been avoiding adding those changes until I saw that in order to pass the CI check I had to include the `dms` changes. My last commit (`remove duplicate iso pairs` d5d6ac7) would not pass the check, and would only pass if I included the `dms` changes in the last commit (`make autofill` 9c6c239).

**Comment by KaimingTao** [comment]
> > @zachandfox this paper is a published preprint, we don't need to reenter it. Please ignore all the files that start with `dms`, you don't need to submit them. Currently, we have an issue between database and website, may take some time to update it.,
> 
> The `dms` changes were done by running `make autofill`, and I had been avoiding adding those changes until I saw that in order to pass the CI check I had to include the `dms` changes. My last commit (`remove duplicate iso pairs` [d5d6ac7](https://github.com/hivdb/covid-drdb-payload/commit/d5d6ac7485c0077b313773c87be3b425e0940df8)) would not pass the check, and would only pass if I included the `dms` changes in the last commit (`make autofill` [9c6c239](https://github.com/hivdb/covid-drdb-payload/commit/9c6c239e9f038155fc8d0d5819d2ee274a8da642)).

@zachandfox I've solved the dms problem, please update your local repositories, both the `covid-drdb` and `covid-drdb-payload`

**Comment by KaimingTao** [comment]
@zachandfox please just update Aggarwal21 to Aggarwal22. Please don't recreate Aggarwal22. Also please add a new item in articles_preprint_doi.csv table with new `ref_name` and the preprint `doi`

**Comment by zachandfox** [comment]
Ah, I misunderstood that this is an update, will do

**Comment by KaimingTao** [comment]
@zachandfox Aggarwal21 and Aggarwal22 should be one record in the article.csv file. Please remove all things from the preprint Aggarwal21, just keep Aggarwal22.

**Pull request merged**
