### PR TITLE
 Reynolds - 10.1126/science.abq1841 #641 

### PR DESCRIPTION
**Pull request by zachandfox**
Reynolds - 10.1126/science.abq1841 #641

### CODE REVIEW

**Comment by zachandfox** [comment]
This paper specifies the infection variant but does not do so at the individual-level source data (aside from the Omicron CP subjects), and so I was not able to specify the infection variant, and I wasn't sure what infection date to use either.

**Comment by KaimingTao** [comment]
> I'm not sure what potency type to use in this case

It's NT50.

**Comment by KaimingTao** [comment]
> This paper specifies the infection variant but does not do so at the individual-level source data (aside from the Omicron CP subjects), and so I was not able to specify the infection variant, and I wasn't sure what infection date to use either.

I see several subjects were infected multiple times. I'll prepare the infection variants data for you. Please wait.

**Comment by KaimingTao** [comment]
[subject_infections.xlsx](https://github.com/hivdb/covid-drdb-payload/files/9883287/subject_infections.xlsx)

@zachandfox  please use these data as subject infection. Some of them were infected >=2 times, but it's not possible to know the accurate data, for these subjects I just provide two infections.

**Pull request merged**
