### PR TITLE
 Branche23 - 10.1101/2023.01.31.23285306 #754 

### PR DESCRIPTION
**Pull request by zachandfox**
Branche23 - 10.1101/2023.01.31.23285306 #754

### CODE REVIEW

**Comment by zachandfox** [comment]
@KaimingTao in this paper, they are comparing BA1-based and BA4/5-based mRNA bivalent vaccination efficacies, and I was not sure how to represent this in the vaccinations table. At the moment they are all treated as "mRNA-bivalent", even though the variants they are based on differ.

**Comment by zachandfox** [comment]
As well, I used the known values (n, GMT) of the not-infected and total (infected+non-infected) groups to calculate the GMT potency values for the infected group. Because these values did not come from a specific table, I labeled their sections as the same as the not-infected group. If you would like to see my work for this I can provide it.

**Comment by KaimingTao** [comment]
> @KaimingTao in this paper, they are comparing BA1-based and BA4/5-based mRNA bivalent vaccination efficacies, and I was not sure how to represent this in the vaccinations table. At the moment they are all treated as "mRNA-bivalent", even though the variants they are based on differ.

It's ok.

**Comment by KaimingTao** [comment]
> As well, I used the known values (n, GMT) of the not-infected and total (infected+non-infected) groups to calculate the GMT potency values for the infected group. Because these values did not come from a specific table, I labeled their sections as the same as the not-infected group. If you would like to see my work for this I can provide it.

I suggest to exclude `with and without` group data for now.

**Comment by zachandfox** [comment]
Because I was able to find the `with` data, I only collected `with` and `without` and not `with and without`, because it would be redundant. Do you want me to collect the `with and without` data, and put it in the `excluded` folder?

**Comment by KaimingTao** [comment]
> Because I was able to find the `with` data, I only collected `with` and `without` and not `with and without`, because it would be redundant. Do you want me to collect the `with and without` data, and put it in the `excluded` folder?

@zachandfox yes, I think so.

**Pull request merged**
