### PR TITLE
Add Yu22

### PR DESCRIPTION
**Pull request by zachandfox**

### CODE REVIEW

**Comment by KaimingTao** [comment]
1) Please remove one data from Figure 1C, the plasma without previous vaccination.
2) in `subject_history` table, please change `vaccinated_bti`'s iso_name to `Omicron/BA.1 full genome`, `hCoV-19/South Africa/CERI-KRISP-K032307/2021` is BA.2. 
Because `Omicron/BA.1 full genome` hasn't been added to `isolates` table, please add it, the mutation list can be found here: https://github.com/hivdb/covid-drdb-payload/blob/master/tables/variant_consensus.csv

**Comment by zachandfox** [comment]
2. How shall I add `Omicron/BA.1 full genome` to the `isolates` table? Do you mean that I write the mutation in the `iso_name` column, and `Omicron/BA.1 full genome` in the `var_name` column?

**Comment by zachandfox** [comment]
...Or rather, how does the mutation list in `variant_consensus` factor into adding `Omicron/BA.1 full genome` to the `isolates` table?

**Comment by KaimingTao** [comment]
> ...Or rather, how does the mutation list in `variant_consensus` factor into adding `Omicron/BA.1 full genome` to the `isolates` table?

You can copy the `Omicron/BA.1` from `variant_consensus` to `isolate_mutations`, just change the `iso_name` to `BA.1 full genome`, the `var_name` should be `Omicron/BA.1`.

**Pull request merged**
