### PR TITLE
 Wang21m - 10.1038/s41467-022-31929-6 #460 

### PR DESCRIPTION
**Pull request by zachandfox**
Wang21m - 10.1038/s41467-022-31929-6 #460

### CODE REVIEW

**Comment by zachandfox** [comment]
@KaimingTao the published version of this paper includes GenBank ID's for the isolates (16 of them); do I need to add these in? The isolates used now are the same as before

**Comment by KaimingTao** [comment]
> @KaimingTao the published version of this paper includes GenBank ID's for the isolates (16 of them); do I need to add these in? The isolates used now are the same as before

If the assay is `live virus` we can try to use the genbank accession number, please make sure use the corresponding virus with same variant type.

**Comment by zachandfox** [comment]
^[this commit](https://github.com/hivdb/covid-drdb-payload/pull/550/commits/de8a455dcc8871e1d35c1ecf76cdbbdd2b93adcc) is an example of what adding an isolate from the genbank numbers will look like. Note that I only know the variant for it based on the Stanford sequence report because the variant name is not provided on its genbank entry page. 

Will this work @KaimingTao? I would also like for you to make sure that it is `live virus` and not a spike-protein assay (this I wasn't sure)

**Comment by KaimingTao** [comment]
@zachandfox the paper said it's using recombinant virus, so I think for iso_name we just need the spike mutations.

**Pull request merged**
