### PR TITLE
 Wang23 - 10.1101/2023.02.07.527406 #761 

### PR DESCRIPTION
**Pull request by zachandfox**
Wang23 - 10.1101/2023.02.07.527406 #761

### CODE REVIEW

**Comment by zachandfox** [comment]
Do we need to keep track of variant synonyms? In this paper, a few isolates are represented one way (`BE.1.1.1`,`BF.14`), but are represented in the repo as their parent/close-relative forms w/ changes in their names (`BA.4/5 Spike:K444T`,`BA.4/5 Spike:+N450D`, respectively).

**Comment by zachandfox** [comment]
(Draft: I forgot to include the mAb fold values, adding now)

**Comment by zachandfox** [comment]
image

@KaimingTao when recording IC50 fold values, are we able to record negative values like that shown here in figure 6b? I did not see current examples in the repo that also have negative values

**Comment by KaimingTao** [comment]
> Do we need to keep track of variant synonyms, if so what are our rules around this step? In this paper, a few isolates are represented one way (`BE.1.1.1`,`BF.14`), but are represented in the repo as their parent/close-relative forms w/ changes in their names (`BA.4/5 Spike:K444T`,`BA.4/5 Spike:+N450D`, respectively). When adding `BA.4/5 Spike:+N450D`, I wasn't sure if it should have been that or `BF.14`).

Please use old way for now. We may change sometime in the future.

**Comment by KaimingTao** [comment]
> image
> 
> @KaimingTao when recording IC50 fold values, are we able to record negative values like that shown here in figure 6b? I did not see current examples in the repo that also have negative values

@zachandfox For fold values, the positive values should be used as is, the negative values should be used as `1/(negative value)`

**Comment by KaimingTao** [comment]
@zachandfox for this fold change value, I made a mistake, it's versed, negative values should be treated at positive values, and positive values should be treated as 1/value

**Pull request merged**
