### PR TITLE
 Uriu23b - 10.1101/2023.09.07.556636

### PR DESCRIPTION
**Pull request by shegocaga**
Uriu23b - 10.1101/2023.09.07.556636 #954

### CODE REVIEW

**Comment by shegocaga** [comment]
I'm not sure what upper-limit to use for the IC50 values

**Comment by KaimingTao** [comment]
@shegocaga please remove Figure 1E data. It's not NT50 assay.

For IC50 please use use the Figure 1J row 4.

775 ug/ml for Beb
26042 for Sot
4200 for Cil
2600 for Tix
2100 for Cil + Tix

**Comment by shegocaga** [comment]
Were you wanting me to only collect the 4th row of Figure 1J and remove the first 3 rows? 
Also, were you wanting me to use those values exactly and also use  `ug/ml` as the units? 
I thought you might be asking me to change the values to `ug/ml` so that we may find a suitable upper-limit, but then the error comes from using these units.

**Comment by KaimingTao** [comment]
@shegocaga please multiple the value by 1000 and use ng/ml, otherwise a lot of thing need to be changed. Many thanks.

**Comment by shegocaga** [comment]
In order to fit the potency values into `ng/ml`, I set the upper-limit of values to 1,000,000

**Pull request merged**
